apiVersion: v1
kind: Pod
metadata:
  name: mcc-pytorch # Change this to your job name
spec:
  containers:
  - name: mcc-pt
    image: eddychu/mcc-pytorch:latest
    # image: ubuntu
    # imagePullPolicy: Always
    resources:
      limits:
        memory: 32Gi
        cpu: 16000m
        nvidia.com/gpu: "1"
        ephemeral-storage: "100Gi"
      requests:
        memory: 32Gi
        cpu: 16000m
        nvidia.com/gpu: "1"
        ephemeral-storage: "100Gi"
    command: ["sh", "-c"]
    args: ["sleep 36500"] # sleep for 365000 seconds, i.e., 4 days. However, any pod will be deleted after 6 hours. need to change this to your command
    volumeMounts:
    - mountPath: /pv
      name: bx-vol
  volumes:
  - name: git-repo
    emptyDir: {}
  - name: bx-vol
    persistentVolumeClaim:
      claimName: eddy-vol
  restartPolicy: Never
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: nvidia.com/gpu.product
  #           operator: In
  #           values:
  #           - NVIDIA-A100-SXM4-80GB
  #           - NVIDIA-A10
  #           - NVIDIA-A40
  #           - NVIDIA-RTX-A6000
  #           - Quadro-RTX-8000
  #           - NVIDIA-3090
  #           - NVIDIA-2080
